version: '2'
tasks:
  #
  # BUILDING
  #
  prebuild:
    cmds:
      - mkdir -p build/

  build:
    cmds:
      - task prebuild
      - task build:linux
      - task build:windows

  build:linux:
    cmds:
      - mkdir -p releases/    
      - docker build -f Dockerfile -t amyrahmady/samp-node-build-linux . --build-arg PLUGIN_VERSION={{ .PLUGIN_VERSION }}
      - docker run -v=$(pwd)/test:/work/test -v=$(pwd)/releases:/work/releases amyrahmady/samp-node-build-linux

  build:windows:
    dir: build
    cmds:    
      - mkdir -p ../releases
      - rm -rf *
      - cmake .. -DPLUGIN_VERSION={{ .PLUGIN_VERSION }} -A Win32 
      - cmake --build . --config Release
      - cpack && mv cpack/*.zip ../releases

  #
  # TESTING
  #
  test:
    cmds:
      - sampctl package ensure && sampctl package build
      - cd test && sampctl server run