name: CI
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          mkdir build \
          && cd build \
          && cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -A Win32 \
          && cmake --build . --config $BUILD_TYPE \
          && cpack && mv cpack/*.zip ../releases  
          
  linux:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          apt install -y libc6-dev-i386
          mkdir build \
          && cd build \
          && cmake .. -DCMAKE_BUILD_TYPE=$ENV{BUILD_TYPE} \
          && cmake --build . --config $ENV{BUILD_TYPE} \
          && cpack && mv cpack/*.zip ../releases

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [windows, linux]
    steps:
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: 'releases/*'
            draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 