name: CI
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${ { matrix.name } }
    runs-on: ${ { matrix.os } }
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-16.04],
        include:
          - os: windows-latest
            name: "windows"
            extension: "zip"

          - os: ubuntu-16.04
            name: "linux"
            extension: "tar.gz"

    steps:
      - uses: actions/checkout@v1

      - name: configure
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=$ENV{BUILD_TYPE}

      - name: build
        run: cmake --build . --config $ENV{BUILD_TYPE}
          
  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build    

    steps:
      - name: package
        run: cpack && mv cpack/*.${{ matrix.extension }} ../releases

      - name: release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false 
          
      - uses: actions/upload-artifact@v1
        with:
          path: releases/
          name: samp-node-${{ github.ref }}-${{ matrix.name }}.${{ matrix.extension }}