name: CI
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  windows:
    runs-on: windows-2016
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          mkdir build \
          && cd build \
          && cmake .. -A Win32 \
          && cmake --build . --config $BUILD_TYPE \
          && cpack && mv cpack/*.zip ../releases  
          
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build
        run: |
          docker build -f Dockerfile -t amyrahmady/samp-node-build-linux . && \
          docker run -v=$(pwd)/test:/work/test -v=$(pwd)/releases:/work/releases amyrahmady/samp-node-build-linux

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [windows, linux]
    steps:
      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: 'releases/*'
            draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 