name: CI
on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-16.04]
        include:
          - os: windows-latest
            name: "windows"
            extension: "zip"
          - os: ubuntu-16.04
            name: "linux"
            extension: "tar.gz"                
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Build
        shell: bash
        run: |
          mkdir build \
          && cd build \
          && cmake .. -DCMAKE_BUILD_TYPE=$ENV{BUILD_TYPE} -A Win32 \
          && cmake --build . --config $ENV{BUILD_TYPE}
          && cpack && mv cpack/*.${{ matrix.extension }} ../releases 
        if: matrix.runs-on == 'windows-latest'
      - name: Build
        shell: bash
        run: |
          mkdir build \
          && cd build \
          && cmake .. -DCMAKE_BUILD_TYPE=$ENV{BUILD_TYPE} \
          && cmake --build . --config $ENV{BUILD_TYPE}
          && cpack && mv cpack/*.${{ matrix.extension }} ../releases 
        if: matrix.runs-on == 'ubuntu-16.04'                

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    uses: softprops/action-gh-release@v1
    if: startsWith(github.ref, 'refs/tags/')
    with:
        files: 'releases/*'
        draft: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 